### ISSUE TITLE
[SUGGESTION] Reduce frequence of battle towers

### ISSUE THREAD

**Issue by ST-DDT** [n643064/BattleTowers#4]
Currently, there are too many battle towers. Is there a way to reduce the frequence of a tower generating?
I can see the battle towers in every direction.

Or is there a way/config I can manually increase the distance between the towers (Like 5x it; 500->2500)?

![grafik](https://github.com/user-attachments/assets/e1af409b-9364-43d2-9dd4-ce60f2838511)

**Comment by suerion** [comment]
On the mod side, we also need an config to change the distance., it is really to much

**Comment by suerion** [comment]
> Currently, there are too many battle towers. Is there a way to reduce the frequence of a tower generating? I can see the battle towers in every direction.
> 
> Or is there a way/config I can manually increase the distance between the towers (Like 5x it; 500->2500)?
> 
> ![grafik](https://private-user-images.githubusercontent.com/1579362/365638827-e1af409b-9364-43d2-9dd4-ce60f2838511.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0ODkzNDgsIm5iZiI6MTcyODQ4OTA0OCwicGF0aCI6Ii8xNTc5MzYyLzM2NTYzODgyNy1lMWFmNDA5Yi05MzY0LTQzZDItOWRkNC1jZTYwZjI4Mzg1MTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDlUMTU1MDQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjZmNjQwNTE0NzllMTNkMzE2OTMxNmQ3MTgzZGE4ZGVjYjk4MTcyY2MzMjNiZDEwMjA5YmRjZTVlYjZhMmMyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Td-uVEexvPcp_e1ML0c0_1nnDDXDsh85NCkvXr6qmbE)

If you use the datapack, you could change the file -> 

https://github.com/n643064/BattleTowers/blob/master/data/battle_towers/worldgen/structure_set/overworld.json

    "spacing": 24,
    "separation": 18
    
    Spacing is need allways being higher than separation

**Comment by suerion** [comment]
@ST-DDT

**Comment by n643064** [comment]
> On the mod side, we also need an config to change the distance., it is really to much

The "mod" files are just repackaged datapacks, generated by modrinth; they don't contain any code. If I ever do make this into an actual mod, tower generation will be fully configurable.

**Comment by suerion** [comment]
Okey, would be nice, if yes, i would love it, (i will compile the json with other spacing settings) would be fine for me yet :)
