### ISSUE TITLE
[Suggestion] Increase minimum size of towers

### ISSUE THREAD

**Issue by ST-DDT** [n643064/BattleTowers#5]
Towers with a single level look weird, especially if they are floating randomly in the ocean.

![{88689946-D912-4B09-8FFC-A7183D529D5E}](https://github.com/user-attachments/assets/02552e07-81fb-4fc3-8787-f691c3eb2f78)

Maybe set the minimum to 3 or 5 levels?

**Comment by n643064** [comment]
I don't think this is doable with just structure files; I'd have to make this an actual mod.
